version: '3.9'

volumes:
  servervol:
    name: servervol
    driver: local
    driver_opts:
      type: none
      device: ./serverdata
      o: bind

services:
  server:
    image: node:latest
    container_name: server
    working_dir: /app
    volumes:
      - ./server:/app
      - servervol:/serverdata
    ports:
      - "80:80"
    command: npm start

  database:
    image: postgres
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Qwerty1!
      - POSTGRES_DB=db

  adminer:
    image: adminer
    restart: always
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    ports:
      - "5432:8080"