version: '3.9'

services:
  server:
    image: node:alpine
    container_name: server
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "80:80"
    command: npm start

  database:
    image: postgres
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Qwerty1!
      - POSTGRES_DB=db

  adminer:
    image: adminer
    restart: always
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    ports:
      - "81:8080"


  stats:
    image: influxdb
    ports:
      - "82:8086"
    volumes:
      - ./influxDB:/var/lib/influxdb2
      #- ./influxconfig/config.yml:/etc/influxdb2/config.yml
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Qwerty1!
      - DOCKER_INFLUXDB_INIT_ORG=OlliOy
      - DOCKER_INFLUXDB_INIT_BUCKET=site-statistics
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=olipakerranyksipienidatapankki